"""Regenerate canonical normalization data; no build/runtime dependency on Python."""
from pathlib import Path
import gzip
from urllib.request import urlopen

VERSION = "17.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"

def fetch(name):
    with urlopen(BASE + name, timeout=30) as response:
        return response.read()

raw = fetch("UnicodeData.txt").decode()
props = fetch("DerivedNormalizationProps.txt").decode()
excluded = set()
for line in props.splitlines():
    fields = line.split("#")[0].split(";")
    if len(fields) < 2 or fields[1].strip() != "Full_Composition_Exclusion":
        continue
    span = fields[0].strip().split("..")
    excluded.update(range(int(span[0], 16), int(span[-1], 16) + 1))

decompositions, classes, compositions = {}, {}, {}
for line in raw.splitlines():
    f = line.split(";")
    c = int(f[0], 16)
    if int(f[3]):
        classes[c] = int(f[3])
    if f[5] and not f[5].startswith("<"):
        parts = [int(x, 16) for x in f[5].split()]
        decompositions[c] = parts
        if len(parts) == 2 and c not in excluded:
            compositions[tuple(parts)] = c

lines = [f"// Code generated by internal/generate_unicode.py from Unicode {VERSION}. DO NOT EDIT.",
         "// Source: https://www.unicode.org/Public/17.0.0/ucd/ (see UNICODE_LICENSE.txt).",
         "package drivesync", "var canonicalDecomposition = map[rune][]rune{"]
for c, parts in sorted(decompositions.items()):
    lines.append(f"0x{c:x}:{{{','.join(f'0x{x:x}' for x in parts)}}},")
lines += ["}", "var canonicalClass = map[rune]int{"]
for c, cl in sorted(classes.items()):
    lines.append(f"0x{c:x}:{cl},")
lines += ["}", "var canonicalComposition = map[[2]rune]rune{"]
for (a, b), c in sorted(compositions.items()):
    lines.append(f"{{0x{a:x},0x{b:x}}}:0x{c:x},")
lines += ["}"]
Path("unicode_tables.go").write_text("\n".join(lines) + "\n")
Path("testdata/NormalizationTest.txt.gz").write_bytes(gzip.compress(fetch("NormalizationTest.txt"), mtime=0))
with urlopen("https://www.unicode.org/license.txt", timeout=30) as response:
    Path("UNICODE_LICENSE.txt").write_bytes(response.read())
